### ISSUE TITLE
Proton Mail and SimpleLogin domains marked in your disposable emails list

### ISSUE THREAD

**Issue by Nikola-Test-for-Proton** [groundcat/disposable-email-domain-list#5]
Hi, this is Nikola.

I work in Proton's (and SimpleLogin's) Anti-Abuse team and noticed that some of our domains are present your list of disposable emails. To be more precise, protonmail.com and protonmail.ch, along with SimpleLogin's dralias.com, 8alias.com, and 8shield.net are included. Could we trouble you to clarify why this is the case and whether it would be possible to correct it? 

We would appreciate it if you could look into this for us accordingly.

Your patience and understanding are greatly appreciated.

**Comment by groundcat** [comment]
Hello, and thank you for informing me. Because this list is for disposable emails collected from external [sources](https://github.com/groundcat/disposable-email-domain-list/blob/master/sources.txt), and I do not intend to include forwarders to this list, Proton and SimpleLogin domains will be added to the allowlist to be excluded from this list. Will update soon.
